# Generated by Django 4.0.1 on 2022-02-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agemodifiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agemodifier',
            old_name='age_from',
            new_name='age_end',
        ),
        migrations.RenameField(
            model_name='agemodifier',
            old_name='age_to',
            new_name='age_start',
        ),
    ]
