# Generated by Django 4.0.1 on 2022-02-02 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridetypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excitement_rating', models.IntegerField()),
                ('intensity_rating', models.IntegerField()),
                ('nausea_rating', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('ridename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridetypes.ridename')),
                ('ridetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridetypes.ridetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
