# Generated by Django 4.0.1 on 2022-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='excitement_rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='intensity_rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='nausea_rating',
            field=models.PositiveIntegerField(),
        ),
    ]
