# Generated by Django 4.0.1 on 2022-02-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ridebonusvalue', models.IntegerField()),
                ('excitement_value', models.IntegerField()),
                ('intensity_value', models.IntegerField()),
                ('nausea_value', models.IntegerField()),
                ('default_excitement', models.IntegerField(blank=True, null=True)),
                ('default_intensity', models.IntegerField(blank=True, null=True)),
                ('default_nausea', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_visible', models.BooleanField()),
                ('excitement_modifier', models.IntegerField(default=0)),
                ('intensity_modifier', models.IntegerField(default=0)),
                ('nausea_modifier', models.IntegerField(default=0)),
                ('ridetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridetypes.ridetype')),
            ],
        ),
    ]
