# Generated by Django 4.0.1 on 2022-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridetypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridename',
            name='excitement_modifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ridename',
            name='intensity_modifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ridename',
            name='nausea_modifier',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='default_excitement',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='default_intensity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='default_nausea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='excitement_value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='intensity_value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='nausea_value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ridetype',
            name='ridebonusvalue',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
